### ISSUE TITLE
上传GD一段时间后报错

### ISSUE THREAD

**Issue by madlaxcb** [gaowanliang/OneDriveUploader#20]
ovh法国机器，系统是ubuntu，上传GD一段时间后报错，试过几次了，看样子是发送TG信息的请求频率太高了？

/root/LightUploader -c /root/admin@XXX.XXX.json -t 1 -f "XXXX" -tgbot "XXXXXX" -uid XXXXX

```
2022/03/09 14:43:47 Telegram Send Error:Too Many Requests: retry after 122
panic: Telegram Send Error:Too Many Requests: retry after 122

goroutine 1 [running]:
log.Panicf({0xc0000de620, 0x22}, {0xc0017211d8, 0xc0017211c8, 0x3})
        D:/program_app/go/src/log/log.go:361 +0x67
main.botSend({0x7ffc536bb31f, 0x95bbf8}, {0x7ffc536bb353, 0xc00013407e}, {0xc00049a7c0, 0x36})
        D:/program_data/go/LightUploader/main.go:218 +0x565
main/googledrive.UploadAllFile({0xc000134050, 0x43}, {0xc001105d50, 0x1, 0x1}, 0xc0003a2400, 0xc0000001a0, {0xc000028180, 0x11}, 0xc000060280, ...)
        D:/program_data/go/LightUploader/googledrive/gdUpload.go:205 +0x183
main/googledrive.UploadAllFile({0x7ffc536bb2ea, 0x2d}, {0x0, 0x0, 0x0}, 0xc0003a2400, 0xa, {0xc000028180, 0x11}, 0xc000060280, ...)
        D:/program_data/go/LightUploader/googledrive/gdUpload.go:253 +0xb6c
main/googledrive.Upload({0x7ffc536bb2c5, 0x1c}, {0x7ffc536bb2ea, 0x2d}, 0x100000000000000, 0x98a888, 0x10, 0x10, {0x95bd94, 0x2}, ...)
        D:/program_data/go/LightUploader/googledrive/gdUpload.go:435 +0x414
main.main()
        D:/program_data/go/LightUploader/main.go:375 +0x101d

```

**Comment by gaowanliang** [comment]
TG API 有限制，原来的时候把他设置成Panic了，最新修复版本 [v2.0.2-fix2](https://github.com/gaowanliang/LightUploader/releases/tag/v2.0.2-fix2) 直接忽略了API错误，此错误不影响主体功能，也不影响后续的发送，故直接屏蔽了
